In [30]:
import pandas as pd

final=pd.read_csv('final.csv')

In [31]:
final.drop(['firefighter_cnt'], axis=1, inplace=True)

,x,y,h3_address,neighbours,neighbours_centroids,caslt_cnt,dth_dnv_cnt,se_dnv_cnt,sl_dnv_cnt,wnd_dnv_cnt,...,park_cnt,firefighter_cnt,crossroad_cnt,도로10이하_cnt,도로10_20_cnt,도로20_30_cnt,도로30이상_cnt,child_cnt,silver_cnt,crosswalk_cnt
0,126.981851,37.583372,8930e1dab47ffff,"['8930e1dab0bffff', '8930e1dab57ffff', '8930e1...","[(37.58613392049726, 126.98056894996715), (37....",0,0,0,0,0,...,0,0,1,6,0,1,0,0,0,0
1,127.037602,37.638996,8930e1c2287ffff,"['8930e1c2287ffff', '8930e1c2297ffff', '8930e1...","[(37.63901298097283, 127.03741299155716), (37....",5,0,4,1,0,...,0,0,2,5,0,0,0,8,0,4
2,127.087740,37.600075,8930e1c038fffff,"['8930e1c0313ffff', '8930e1c038bffff', '8930e1...","[(37.59689598894049, 127.08903919595633), (37....",0,0,0,0,0,...,0,0,0,6,0,0,0,2,0,0
3,127.086163,37.548920,8930e1c1e43ffff,"['8930e1c1e57ffff', '8930e1c1e43ffff', '8930e1...","[(37.551676147473344, 127.08524015098106), (37...",0,0,0,0,0,...,1,0,0,0,0,0,0,5,0,0
4,127.052611,37.474410,8930e1c846fffff,"['8930e1c846bffff', '8930e1c80d7ffff', '8930e1...","[(37.47192197069472, 127.04972273346766), (37....",0,0,0,0,0,...,0,0,0,4,0,0,0,3,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1195,127.001913,37.642277,8930e1d1b87ffff,"['8930e1d194bffff', '8930e1d1b97ffff', '8930e1...","[(37.646341731057056, 127.00127219315168), (37...",0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1196,126.857092,37.523550,8930e0acdc3ffff,"['8930e0acdd7ffff', '8930e0acdcbffff', '8930e0...","[(37.52580349202538, 126.85791386202587), (37....",0,0,0,0,0,...,0,0,1,7,0,0,0,8,0,2
1197,126.905564,37.501170,8930e1d9633ffff,"['8930e1d963bffff', '8930e1d9623ffff', '8930e1...","[(37.49854596840169, 126.90536383536052), (37....",0,0,0,0,0,...,0,0,2,6,0,0,0,5,1,7
1198,126.954775,37.482656,8930e036d03ffff,"['8930e036d0fffff', '8930e036d0bffff', '8930e0...","[(37.48080085355876, 126.95621326260232), (37....",9,0,7,2,0,...,0,0,2,4,0,0,0,5,0,9
1199,126.977222,37.476974,8930e0369a7ffff,"['8930e1d9a6bffff', '8930e0369a3ffff', '8930e1...","[(37.48103069970001, 126.97716175650788), (37....",0,0,0,0,0,...,0,0,0,6,0,0,0,3,0,1